name: build-docs

on: [push, pull_request, workflow_dispatch]

permissions:
  contents: write

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        uses: mamba-org/setup-micromamba@v1
        with:
          micromamba-version: "1.5.7-0"
          environment-file: docs-env.yaml
          init-shell: bash
      - name: Sphinx build
        run: sphinx-build source build
        shell: bash -el {0}
      - name: Push site to Github Pages
        uses: Cecilapp/GitHub-Pages-deploy@3.2.2
        with:
          build_dir: build
          branch: gh-pages
          jekyll: no
          
